# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('calendardate', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateEventMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=31)),
                ('m_name', models.CharField(max_length=31)),
                ('s_name', models.CharField(max_length=31)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.TextField()),
                ('joined_date', models.DateField()),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag'),
        ),
        migrations.AddField(
            model_name='dateevent',
            name='dateMedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.DateEventMedia'),
        ),
        migrations.AddField(
            model_name='dateevent',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag'),
        ),
        migrations.AddField(
            model_name='datecalendar',
            name='dateEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.DateEvent'),
        ),
        migrations.AddField(
            model_name='datecalendar',
            name='juliet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Juliet', to='organizer.Person'),
        ),
        migrations.AddField(
            model_name='datecalendar',
            name='romeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Romeo', to='organizer.Person'),
        ),
    ]
